# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: dfbbc8d
_src_path: https://github.com/vivienm/copier-python
build_system: maturin
copyright_holder: Vivien Maisonneuve
copyright_year: 2022
doc_generator: sphinx
forge: github
github_pages: true
github_repo: python-tdigest-ch
github_user: vivienm
license: MIT
package_name: tdigest-ch
project_description: A Python library for estimating quantiles in a stream, using
    ClickHouse t-digest data structure.
project_name: tdigest-ch
project_type: library
python_version: '3.10'
user_email: v.maisonneuve@gmail.com
user_name: Vivien Maisonneuve
