[project]
name = "tdigest-ch"
description = "A Python library for estimating quantiles in a stream, using ClickHouse t-digest data structure."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Vivien Maisonneuve", email = "v.maisonneuve@gmail.com"},
]
dynamic = ["version"]
dependencies = []

[project.urls]
repository = "https://github.com/vivienm/python-tdigest-ch"
documentation = "https://vivienm.github.io/python-tdigest-ch/"

[project.optional-dependencies]


[build-system]
requires = [
    "pdm-pep517",
    "setuptools-rust",
]
build-backend = "pdm.pep517.api"


[tool.pdm]
package-dir = "src"

[tool.pdm.build]
setup-script = "build.py"
run-setuptools = true

[tool.pdm.dev-dependencies]
black = [
    "black>=22.6.0",
]
flake8 = [
    "flake8>=4.0.1",
    "flake8-docstrings>=1.6.0",
]
isort = [
    "isort>=5.10.1",
]
mypy = [
    "mypy>=0.961",
    "pytest>=7.1.2",
    "setuptools-rust>=1.4.1",
]
pytest = [
    "coverage[toml]>=6.4.4",
    "pytest>=7.1.2",
    "pytest-benchmark>=3.4.1",
    "tdigest>=0.5.2.2",
]
coverage = [
    "coverage[toml]>=6.4.4",
]
sphinx = [
    "furo>=2022.6.21",
    "sphinx>=5.1.0",
]
safety = [
    "safety>=2.1.1",
]
nox = [
    "nox>=2022.1.7",
]

[tool.pdm.version]
source = "scm"


[tool.isort]
profile = "black"


[tool.mypy]
exclude = ["^build/"]

[[tool.mypy.overrides]]
module = [
    "nox",
    "pytest_benchmark.fixture",
    "tdigest_ch._rust",
    "setuptools_rust",
    "tdigest",
]
ignore_missing_imports = true


[tool.pytest.ini_options]
addopts = "--doctest-modules --benchmark-skip"
testpaths = [
    "src",
    "tests",
]


[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
