name: "Continuous integration"

on:
  push:
  pull_request:

jobs:
  nox:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "pdm-project/setup-pdm@main"
      with:
        python-version: "3.8"
    - uses: "actions/checkout@v3"
    - run: "pdm venv create 3.8"
    - run: "pdm install"
    - uses: "actions/upload-artifact@v3"
      with:
        name: "pdm-lockfile"
        path: "./pdm.lock"
        retention-days: 7
    - run: "pdm run nox"
    - uses: "actions/upload-artifact@v3"
      with:
        name: "sphinx"
        path: "./docs/_build/html"
        retention-days: 7

  pages:
    if: "github.ref == format('refs/heads/{0}', github.event.repository.default_branch)"
    needs: "nox"
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/download-artifact@v3"
      with:
        name: "sphinx"
        path: "${{ runner.temp }}/pages/docs"
    - uses: "actions/upload-pages-artifact@v1"
      with:
        path: "${{ runner.temp }}/pages"
    - id: "deployment"
      uses: "actions/deploy-pages@v1"
