name: "Continuous integration"

on:
  push:
  pull_request:

jobs:
  nox:
    strategy:
      matrix:
        include:
        - name: "Run black"
          os: "ubuntu-latest"
          python-version: "3.10"
          nox-session: "black"
        - name: "Run isort"
          os: "ubuntu-latest"
          python-version: "3.10"
          nox-session: "isort"
        - name: "Run flake8"
          os: "ubuntu-latest"
          python-version: "3.10"
          nox-session: "flake8"
        - name: "Run mypy"
          os: "ubuntu-latest"
          python-version: "3.10"
          nox-session: "mypy"
        - name: "Run pytest (3.7)"
          os: "ubuntu-latest"
          python-version: "3.7"
          nox-session: "pytest-3.7"
        - name: "Run pytest (3.8)"
          os: "ubuntu-latest"
          python-version: "3.8"
          nox-session: "pytest-3.8"
        - name: "Run pytest (3.9)"
          os: "ubuntu-latest"
          python-version: "3.9"
          nox-session: "pytest-3.9"
        - name: "Run pytest (3.10)"
          os: "ubuntu-latest"
          python-version: "3.10"
          nox-session: "pytest-3.10"
        - name: "Run audit"
          os: "ubuntu-latest"
          python-version: "3.10"
          nox-session: "audit"
    name: "${{ matrix.name }}"
    runs-on: "${{ matrix.os }}"
    steps:
    - name: "Checkout the repository"
      uses: "actions/checkout@v3"
    - name: "Set up PDM"
      uses: "pdm-project/setup-pdm@main"
      with:
        python-version: "${{ matrix.python-version }}"
    - name: "Resolve dependencies"
      run: "pdm lock"
    - name: "Install Nox"
      run: "pip install --user nox"
    - name: "Run Nox"
      run: "nox"
      env:
        NOXSESSION: "${{ matrix.nox-session }}"
